### ISSUE TITLE
4 tests are failing

### ISSUE THREAD

**Issue by aknuds1** [aio-libs/aiozmq#42]
4 tests are failing for me with aiozmq revision 7ab57b78a532cee4b9cd93eadf25d7b51952e82c, Python 3.4.1 on Windows 7. Is this expected?

I am investigating RPC calls timing out (although my RPC methods finish on time), so I'm wondering if the failing tests may be relevant.

```
Q:\Users\arvek\Repositories\accc-gui\aiozmq [master]> python .\runtests.py                                                                                                                    
Skipping 'events_test': don't check                                                                                                                                                           
..ssssss......................................................................................................................F............................F.......s..........s......s........
........................................................F..ss................................F..ss............................                                                                
======================================================================                                                                                                                        
FAIL: test_server_close (rpc_test.LoopLessRpcTests)                                                                                                                                           
----------------------------------------------------------------------                                                                                                                        
Traceback (most recent call last):                                                                                                                                                            
  File "tests\rpc_test.py", line 615, in test_server_close                                                                                                                                    
    self.loop.run_until_complete(communicate())                                                                                                                                               
  File "C:\Python34\lib\asyncio\base_events.py", line 208, in run_until_complete                                                                                                              
    return future.result()                                                                                                                                                                    
  File "C:\Python34\lib\asyncio\futures.py", line 243, in result                                                                                                                              
    raise self._exception                                                                                                                                                                     
  File "C:\Python34\lib\asyncio\tasks.py", line 321, in _step                                                                                                                                 
    result = next(coro)                                                                                                                                                                       
  File "tests\rpc_test.py", line 606, in communicate                                                                                                                                          
    self.assertEqual(1, len(server._proto.pending_waiters))                                                                                                                                   
AssertionError: 1 != 0                                                                                                                                                                        

======================================================================                                                                                                                        
FAIL: test_server_close (rpc_test.LoopRpcTests)                                                                                                                                               
----------------------------------------------------------------------                                                                                                                        
Traceback (most recent call last):                                                                                                                                                            
  File "tests\rpc_test.py", line 615, in test_server_close                                                                                                                                    
    self.loop.run_until_complete(communicate())                                                                                                                                               
  File "C:\Python34\lib\asyncio\base_events.py", line 208, in run_until_complete                                                                                                              
    return future.result()                                                                                                                                                                    
  File "C:\Python34\lib\asyncio\futures.py", line 243, in result                                                                                                                              
    raise self._exception                                                                                                                                                                     
  File "C:\Python34\lib\asyncio\tasks.py", line 321, in _step                                                                                                                                 
    result = next(coro)                                                                                                                                                                       
  File "tests\rpc_test.py", line 606, in communicate                                                                                                                                          
    self.assertEqual(1, len(server._proto.pending_waiters))                                                                                                                                   
AssertionError: 1 != 0                                                                                                                                                                        

======================================================================                                                                                                                        
FAIL: test_close_on_error (zmq_events_test.ZmqLooplessTests)                                                                                                                                  
----------------------------------------------------------------------                                                                                                                        
Traceback (most recent call last):                                                                                                                                                            
  File "tests\zmq_events_test.py", line 745, in test_close_on_error                                                                                                                           
    check_errno(88, handler.call_args[0][1]['exception'])                                                                                                                                     
  File "Q:\Users\arvek\Repositories\accc-gui\aiozmq\aiozmq\_test_util.py", line 226, in check_errno                                                                                           
    assert exc.errno == errno, (exc, errno)                                                                                                                                                   
AssertionError: (OSError(128, 'Unknown error'), 88)                                                                                                                                           

======================================================================                                                                                                                        
FAIL: test_close_on_error (zmq_events_test.ZmqEventLoopTests)                                                                                                                                 
----------------------------------------------------------------------                                                                                                                        
Traceback (most recent call last):                                                                                                                                                            
  File "tests\zmq_events_test.py", line 745, in test_close_on_error                                                                                                                           
    check_errno(88, handler.call_args[0][1]['exception'])                                                                                                                                     
  File "Q:\Users\arvek\Repositories\accc-gui\aiozmq\aiozmq\_test_util.py", line 226, in check_errno                                                                                           
    assert exc.errno == errno, (exc, errno)                                                                                                                                                   
AssertionError: (OSError(128, 'Unknown error'), 88)                                                                                                                                           

----------------------------------------------------------------------                                                                                                                        
Ran 316 tests in 15.244s                                                                                                                                                                      

FAILED (failures=4, skipped=13)                                                                                                                                                               
```

**Comment by MetaMemoryT** [comment]
:+1: I am getting 9 failures with current master.

```
======================================================================                                           
FAIL: test_server_close (rpc_test.LoopRpcTests)                                                                  
----------------------------------------------------------------------                                           
Traceback (most recent call last):                                                                               
  File "tests\rpc_test.py", line 615, in test_server_close                                                       
    self.loop.run_until_complete(communicate())                                                                  
  File "C:\Python34\lib\asyncio\base_events.py", line 268, in run_until_complete                                 
    return future.result()                                                                                       
  File "C:\Python34\lib\asyncio\futures.py", line 277, in result                                                 
    raise self._exception                                                                                        
  File "C:\Python34\lib\asyncio\tasks.py", line 236, in _step                                                    
    result = next(coro)                                                                                          
  File "tests\rpc_test.py", line 606, in communicate                                                             
    self.assertEqual(1, len(server._proto.pending_waiters))                                                      
AssertionError: 1 != 0                                                                                           
                                                                                                                 
======================================================================                                           
FAIL: test_server_close (rpc_test.LoopLessRpcTests)                                                              
----------------------------------------------------------------------                                           
Traceback (most recent call last):                                                                               
  File "tests\rpc_test.py", line 615, in test_server_close                                                       
    self.loop.run_until_complete(communicate())                                                                  
  File "C:\Python34\lib\asyncio\base_events.py", line 268, in run_until_complete                                 
    return future.result()                                                                                       
  File "C:\Python34\lib\asyncio\futures.py", line 277, in result                                                 
    raise self._exception                                                                                        
  File "C:\Python34\lib\asyncio\tasks.py", line 236, in _step                                                    
    result = next(coro)                                                                                          
  File "tests\rpc_test.py", line 606, in communicate                                                             
    self.assertEqual(1, len(server._proto.pending_waiters))                                                      
AssertionError: 1 != 0                                                                                           
                                                                                                                 
======================================================================                                           
FAIL: test_close_on_error (zmq_events_test.ZmqEventLoopTests)                                                    
----------------------------------------------------------------------                                           
Traceback (most recent call last):                                                                               
  File "tests\zmq_events_test.py", line 755, in test_close_on_error                                              
    check_errno(errno, handler.call_args[0][1]['exception'])                                                     
  File "C:\Users\Sean\p\aiozmq\aiozmq\_test_util.py", line 226, in check_errno                                   
    assert exc.errno == errno, (exc, errno)                                                                      
AssertionError: (OSError(128, 'Unknown error'), 88)                                                              
                                                                                                                 
======================================================================                                           
FAIL: test_force_close_monitor (zmq_events_test.ZmqEventLoopTests)                                               
----------------------------------------------------------------------                                           
Traceback (most recent call last):                                                                               
  File "tests\zmq_events_test.py", line 851, in test_force_close_monitor                                         
    self.loop.run_until_complete(go())                                                                           
  File "C:\Python34\lib\asyncio\base_events.py", line 268, in run_until_complete                                 
    return future.result()                                                                                       
  File "C:\Python34\lib\asyncio\futures.py", line 277, in result                                                 
    raise self._exception                                                                                        
  File "C:\Python34\lib\asyncio\tasks.py", line 236, in _step                                                    
    result = next(coro)                                                                                          
  File "tests\zmq_events_test.py", line 849, in go                                                               
    self.assertIsNone(tr._monitor)                                                                               
AssertionError: <aiozmq.core._ZmqEventProtocol object at 0x0000000004337A58> is not None                         
                                                                                                                 
======================================================================                                           
FAIL: test_implicit_monitor_disable (zmq_events_test.ZmqEventLoopTests)                                          
----------------------------------------------------------------------                                           
Traceback (most recent call last):                                                                               
  File "tests\zmq_events_test.py", line 828, in test_implicit_monitor_disable                                    
    self.loop.run_until_complete(go())                                                                           
  File "C:\Python34\lib\asyncio\base_events.py", line 268, in run_until_complete                                 
    return future.result()                                                                                       
  File "C:\Python34\lib\asyncio\futures.py", line 277, in result                                                 
    raise self._exception                                                                                        
  File "C:\Python34\lib\asyncio\tasks.py", line 236, in _step                                                    
    result = next(coro)                                                                                          
  File "tests\zmq_events_test.py", line 826, in go                                                               
    self.assertIsNone(tr._monitor)                                                                               
AssertionError: <aiozmq.core._ZmqEventProtocol object at 0x0000000004337C88> is not None                         
                                                                                                                 
======================================================================                                           
FAIL: test_close_on_error (zmq_events_test.ZmqLooplessTests)                                                     
----------------------------------------------------------------------                                           
Traceback (most recent call last):                                                                               
  File "tests\zmq_events_test.py", line 755, in test_close_on_error                                              
    check_errno(errno, handler.call_args[0][1]['exception'])                                                     
  File "C:\Users\Sean\p\aiozmq\aiozmq\_test_util.py", line 226, in check_errno                                   
    assert exc.errno == errno, (exc, errno)                                                                      
AssertionError: (OSError(128, 'Unknown error'), 88)                                                              
                                                                                                                 
======================================================================                                           
FAIL: test_force_close_monitor (zmq_events_test.ZmqLooplessTests)                                                
----------------------------------------------------------------------                                           
Traceback (most recent call last):                                                                               
  File "tests\zmq_events_test.py", line 851, in test_force_close_monitor                                         
    self.loop.run_until_complete(go())                                                                           
  File "C:\Python34\lib\asyncio\base_events.py", line 268, in run_until_complete                                 
    return future.result()                                                                                       
  File "C:\Python34\lib\asyncio\futures.py", line 277, in result                                                 
    raise self._exception                                                                                        
  File "C:\Python34\lib\asyncio\tasks.py", line 236, in _step                                                    
    result = next(coro)                                                                                          
  File "tests\zmq_events_test.py", line 849, in go                                                               
    self.assertIsNone(tr._monitor)                                                                               
AssertionError: <aiozmq.core._ZmqEventProtocol object at 0x0000000004C753C8> is not None                         
                                                                                                                 
======================================================================                                           
FAIL: test_implicit_monitor_disable (zmq_events_test.ZmqLooplessTests)                                           
----------------------------------------------------------------------                                           
Traceback (most recent call last):                                                                               
  File "tests\zmq_events_test.py", line 828, in test_implicit_monitor_disable                                    
    self.loop.run_until_complete(go())                                                                           
  File "C:\Python34\lib\asyncio\base_events.py", line 268, in run_until_complete                                 
    return future.result()                                                                                       
  File "C:\Python34\lib\asyncio\futures.py", line 277, in result                                                 
    raise self._exception                                                                                        
  File "C:\Python34\lib\asyncio\tasks.py", line 236, in _step                                                    
    result = next(coro)                                                                                          
  File "tests\zmq_events_test.py", line 826, in go                                                               
    self.assertIsNone(tr._monitor)                                                                               
AssertionError: <aiozmq.core._ZmqEventProtocol object at 0x0000000004C750F0> is not None                         
                                                                                                                 
======================================================================                                           
FAIL: test_pause_reading (zmq_stream_test.ZmqStreamTests)                                                        
----------------------------------------------------------------------                                           
Traceback (most recent call last):                                                                               
  File "tests\zmq_stream_test.py", line 201, in test_pause_reading                                               
    self.loop.run_until_complete(go())                                                                           
  File "C:\Python34\lib\asyncio\base_events.py", line 268, in run_until_complete                                 
    return future.result()                                                                                       
  File "C:\Python34\lib\asyncio\futures.py", line 277, in result                                                 
    raise self._exception                                                                                        
  File "C:\Python34\lib\asyncio\tasks.py", line 236, in _step                                                    
    result = next(coro)                                                                                          
  File "tests\zmq_stream_test.py", line 195, in go                                                               
    self.assertTrue(s2._paused)                                                                                  
AssertionError: False is not true                                                                                
                                                                                                                 
----------------------------------------------------------------------                                           
Ran 353 tests in 14.878s                                                                                         
                                                                                                                 
FAILED (failures=9, skipped=13)                                                                                  
```

**Comment by asvetlov** [comment]
What OS and libzmq version are you using?

**Comment by asvetlov** [comment]
Well, looks like OS is Windows.
Loopless event loop is not intended to be used with Windows.
I should skip all loopless tests.

**Comment by MetaMemoryT** [comment]
windows os,
pyzmq>=14.2.0
